name: 'Setup Git and Git LFS'
description: 'Installs and configures Git and Git LFS for CI environment'

runs:
  using: "composite"
  steps:
    - name: Install Git and Git LFS
      shell: bash
      run: |
        apt-get update -y
        DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends git git-lfs
        git config --global --add safe.directory /__w/SWAGGER/SWAGGER
        # Configure Git LFS
        git lfs install --local
        # Remove existing pre-push hook if it exists
        if [ -f .git/hooks/pre-push ]; then
          rm .git/hooks/pre-push
        fi
        # Reinstall Git LFS hooks
        git lfs update --force
        # Configure Git to skip hooks in CI
        git config --global core.hooksPath /tmp/git-hooks
        mkdir -p /tmp/git-hooks 